sudo: required
dist: trusty
branches:
  only:
  - release
  - dev
git:
  submodules: false
language: c
matrix:
  include:
  - os: osx
node_js:
- 6
cache:
  directories:
  - node_modules
  - $HOME/.electron
before_install:
- if [ "$TRAVIS_BRANCH" = "release" ]; then openssl aes-256-cbc -K $encrypted_fec05b564c85_key -iv $encrypted_fec05b564c85_iv
  -in id_rsa.enc -out packaging/id_rsa -d; fi
install:
- nvm install 6
- npm install electron-builder@next
- npm install -g yarn
- npm install
before_script:
- git clone https://github.com/khalisfoundation/sttm-core.git www/core
- sleep 3
script:
- if [ "$TRAVIS_BRANCH" = "release" ]; then
    npm run test && npm run dist:mac;
  else
    npm test;
  fi
